//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int ID { get; set; }
        public string MONTH { get; set; }
        public string DAY { get; set; }
        public string AFTER_WAKE_UP { get; set; }
        public string AT_UNIVERSITY { get; set; }
        public string AFTER_LESSON_END { get; set; }
        public string AT_NIGHT { get; set; }
        public string NOT_IN_PLAN { get; set; }
    }
}
